/**
*
* Dominic Giglio - CSC110 7:40-9:50 - 2/9/2011
* This is a program that calculates the expected earnings for a hypothetical East Coast
* sales department. I'm chosen to use the "F" notation on my floats to get into the habit of
* conserving memory for when my programs get larger
*
*/

public class SalesPrediction
{
    public static void main(String[] args)
    {
        // First we need to declare the variables used to calculate the predicted sales
        // Always initialize variables when they are declared so we never run into a compiler
        // error when working with variables in our methods
        int totalSales = 4600000;
        float predictedSales = 0.0F;
        
        // Now we calculate the actual amount of total sales that
        // should be generated by our hypothetical slaes department
        predictedSales = totalSales * 0.62F;
        
        // Finally we print out the result of our calculation
        System.out.println("The predicted sales from the East Coast sales department is: $" + predictedSales);
    }
}

